### ISSUE TITLE
Gemfile.lock in repo

### ISSUE THREAD

**Issue by artplan1** [rtfpessoa/yavdb#7]
I started to work on https://github.com/rtfpessoa/yavdb/issues/6 but found some things in repo

Checked in Gemfile.lock.

It can cause issues for users who uses different version of dependencies, so I think it's better to add it to gitignore (I can submit PR)

**Comment by rtfpessoa** [comment]
@artplan1 not sure i understood exactly your comment.

Are you referring to the Gemfile.lock in examples?

If not, we need that file committed to enforce correct versions of dependencies. Check https://bundler.io/v2.0/guides/faq.html#committing-lockfiles-in-libraries as a starting point.
Can you extend on the type of issues?

**Comment by artplan1** [comment]
oh wow, that's new to me
til now I thought it's recommended to exclude it from VCS for gems because of old article by Katz
TIL, thank you :)
